"""Add email column to invitations

Revision ID: 38c57030918b
Revises: 5e74f6506020
Create Date: 2025-06-02 20:33:30.785834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38c57030918b'
down_revision = '5e74f6506020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('invitations_target_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('invitations_inviter_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('inviter_user_id')
        batch_op.drop_column('target_role')
        batch_op.drop_column('target_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_role', postgresql.ENUM('OWNER', 'GUEST', 'RESIDENT', name='residentrole'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('inviter_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('invitations_inviter_user_id_fkey'), 'users', ['inviter_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('invitations_target_user_id_fkey'), 'users', ['target_user_id'], ['id'])
        batch_op.alter_column('code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('used')
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
