"""Add invitation table

Revision ID: 5e74f6506020
Revises: a73494186e6c
Create Date: 2025-06-02 18:19:34.275330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e74f6506020'
down_revision = 'a73494186e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=False))
        batch_op.alter_column('target_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('target_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('code')

    # ### end Alembic commands ###
