"""Add owner_code to address

Revision ID: a73494186e6c
Revises: 807754fdb252
Create Date: 2025-06-02 17:46:35.188185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73494186e6c'
down_revision = '807754fdb252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_code', sa.String(length=16), nullable=False))
        batch_op.create_unique_constraint(None, ['owner_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('owner_code')

    # ### end Alembic commands ###
